version: '3'
services:
  api:
    container_name: travel-buddy-api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    tty: true
    volumes:
      - ./api:/var/www
    ports:
      - "3000:3000"
      - "9000:9000"
    tty: true